# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Default
  demands:
  - Agent.Version -equals 4.251.0

jobs:
- job: BuildAndTest
  displayName: Build and Test with Gradle
  steps:
  - script: java -version
    displayName: Print Java Version
    env:
      JAVA_HOME: $(JAVA_HOME_21_X86)
      PATH: $(JAVA_HOME_21_X86)/bin;$(PATH)
  
  - script: echo %JAVA_HOME%
    displayName: Print JAVA_HOME
  
  - script: icacls gradlew /grant Everyone:F
    displayName: Grant execute permissions to gradlew
  
  - task: JavaToolInstaller@1
    inputs:
      versionSpec: '21'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Gradle@3
    displayName: Run build of the app with gradle
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false
  